### ISSUE TITLE
Checking for install from browser

### ISSUE THREAD

**Issue by Briggybros** [SpaceManiac/McURL2#2]
Hello, on the web side of this, is there a way to check if the user clicking the link has the program installed? Say, it links to a php page and that somehow checks if the user has the required software to open minecraft:// links, if so, give them the server's link, and if not, link them to the download of this tool?

**Comment by SpaceManiac** [comment]
My research in the past has indicated that there's no reliable way to automatically detect whether McURL is already installed cross-browser. This [StackOverflow question](https://stackoverflow.com/questions/836777/how-to-detect-browsers-protocol-handlers) has more information about possible solutions - maybe one of them will help you out. If nothing else works, a simple text instruction to the user might suffice. Let me know what you work out.

**Comment by Briggybros** [comment]
I've just ended up using this solution:

``` javascript
<center><img id="Img" src="play.png" onclick="buttonClick()" /></center>
    <script>
        function buttonClick() {
          if (getCookie("hasMcURL") != "true") {
            var r=confirm("You require McURL to join from your browser. Would you like to download it?");
            if (r==true) {
              var win = window.open("http://wombat.platymuus.com/minecraft/mcurl/", '_blank');
              win.focus();
              document.cookie="hasMcURL=true";
            }
          } else {
            window.open ('minecraft://mc.toomuchminecraft.com/','_self',false);
          }
        }

        function getCookie(cname) {
          var name = cname + "=";
          var ca = document.cookie.split(';');
          for(var i=0; i<ca.length; i++) {
            var c = ca[i].trim();
            if (c.indexOf(name) == 0){ return c.substring(name.length,c.length);}
          }
          return "";
        }
    </script>
```
